export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const GET_LEVEL = "GET_LEVEL";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
